services:
  db:
    container_name: restaurants_db
    image: postgres:17.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5444:5432'
    volumes:
    - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local